language: node_js

node_js:
  - "lts/*"
  - "13"
  - "12"

os:
  - osx
  - linux
  - windows

cache:
  npm: false

script:
  - npm i -g
  - hyperdrive start
  - hyperdrive status

jobs:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode11.3
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode8
